DO
$$
BEGIN
   IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'wmsuser') THEN
      CREATE ROLE wmsuser LOGIN PASSWORD 'wms';
   END IF;
END
$$;

GRANT ALL ON SCHEMA public TO wmsuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO wmsuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO wmsuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO wmsuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO wmsuser;
